apiVersion: v2
name: thanos-query-frontend
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: v0.16.0
keywords:
  - thanos
  - prometheus
home: https://thanos.io/
sources:
  - https://github.com/thanos-io/thanos
  - https://github.com/thanos-community/helm-charts
icon: https://raw.githubusercontent.com/thanos-io/thanos/master/docs/img/Thanos-logo_fullmedium.png
maintainers:
  - name: spencergilbert
